In [12]:
#list comprehension
a=[1,2,2,2,4,5,5]
mylist=[item*4 for item in a]
mylist
mylist=[item*4 for item in a if item > 4] 
mylist

[20, 20]

In [10]:
#set 
sA=set(a)
sA
sB=set([4,5,6,7])
sB
# set operation,union,intersection,difference
sA-sB
sA & sB

{4, 5}

In [13]:
from numpy import array
mm=array((1,1,1))
pp=array((1,2,3))
mm+pp

array([2, 3, 4])

In [17]:
from numpy import mat
ss=mat([1,2,3])
ss
pyList=[2,3,4]
#.T method
ss*mat(pyList).T

matrix([[20]])

In [5]:
import numpy as np
ss=np.mat([1,2,3])
ss_shape=np.shape(ss)
print(ss_shape)
# list to dimension matrix
# multidimensional array
pyList1=[1,2,3]
pyList2=[2,3,4]
mm=np.mat([pyList1,pyList2])
mm

(1, 3)


matrix([[1, 2, 3],
        [2, 3, 4]])

In [18]:
mm.mean()
st=np.mat([4,5,1])
#st.sort()
st.argsort()


matrix([[2, 0, 1]])